### ISSUE TITLE
Create Readme File 

### ISSUE THREAD

**Issue by Evildricks** [Evildricks/Weather_App_Python#2]
Create a readme file for this project.
https://github.com/amittri1025/Whatsapp-Link-Gen.git
take inspiration from this readme file , and try to create a similar one

**Comment by fazil-syed** [comment]
I would like to work on this and can you specify what you want included in the readme

**Comment by aryankshl** [comment]
hey @Evildricks can you assign this to me?

**Comment by Aashi19234** [comment]
Can you assign this to me please?

**Comment by PriyanshiiAgrawall** [comment]
Please assign this issue to me @Evildricks . I want to work on it.
